name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make
    - name: Run CraftOSTest
      run: make test || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
    
  build-basic:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libpoco-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --without-ncurses --without-png --without-sdl_mixer --with-html
        make
    - name: Run CraftOSTest
      run: make test || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-standalone:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev nodejs
    - name: Build standalone ROM
      run: |
        git clone https://github.com/MCJack123/craftos2-rom
        cd craftos2-rom
        node ../packStandaloneROM.js
        cd ..
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --with-standalone-rom=craftos2-rom/fs_standalone.cpp
        make
    - name: Run CraftOSTest
      run: make test || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-cct-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM & CC:T
      run: |
        sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
        git clone --branch v1.15.2-1.89.1 https://github.com/SquidDev-CC/CC-Tweaked ../CC-Tweaked
        rm -r ../CC-Tweaked/src/test/resources/test-rom/spec/programs/turtle ../CC-Tweaked/src/test/resources/test-rom/spec/programs/command ../CC-Tweaked/src/test/resources/test-rom/spec/programs/pocket ../CC-Tweaked/src/test/resources/test-rom/spec/apis/redstone_spec.lua ../CC-Tweaked/src/test/resources/test-rom/spec/apis/gps_spec.lua ../CC-Tweaked/src/test/resources/test-rom/spec/programs/redstone_spec.lua ../CC-Tweaked/src/test/resources/test-rom/spec/programs/gps_spec.lua 
        sed 's/expect\(fs\.getCapacity\(""\)\)\:eq\(10000000\)//' ../CC-Tweaked/src/test/resources/test-rom/spec/apis/fs_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/apis/fs_spec.lua
        sed 's/short_src = "startup.lua", source = "@startup.lua"/short_src = "\/rom\/startup.lua", source = "@\/rom\/startup.lua"/' ../CC-Tweaked/src/test/resources/test-rom/spec/base_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/base_spec.lua
        sed 's/expect\(clear\)\:called\(1\)/expect\(clear\):called\(2\)/' ../CC-Tweaked/src/test/resources/test-rom/spec/programs/clear_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/programs/clear_spec.lua
        sed 's/hdd/test-rom/' ../CC-Tweaked/src/test/resources/test-rom/spec/programs/drive_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/programs/drive_spec.lua
        sed 's/wget run <url>/wget run <url> \[args...\]/' ../CC-Tweaked/src/test/resources/test-rom/spec/programs/http/wget_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/programs/http/wget_spec.lua
        sed 's/startup\.lua/test-files\/out\.txt/' ../CC-Tweaked/src/test/resources/test-rom/spec/apis/fs_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/apis/fs_spec.lua
        sed 's/expect\.error\(io\.lines, ""\)\:eq\("\/\: No such file"\)/expect\.error\(io\.lines, ""\):eq\("bad argument \#1 to 'lines' \(\: Is a directory\)"\)/' ../CC-Tweaked/src/test/resources/test-rom/spec/apis/io_spec.lua > ../CC-Tweaked/src/test/resources/test-rom/spec/apis/io_spec.lua
        echo '_G.failed_tests = actual_count - test_status.pass' >> ../CC-Tweaked/src/test/resources/test-rom/mcfly.lua
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make
    - name: Run CC:T McFly Tests
      run: ./craftos --mount-ro test-rom=../CC-Tweaked/src/test/resources/test-rom --headless --script CCT-Test-Bootstrap.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/test-log.txt
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
      
