name: CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make
    - name: Run CraftOSTest
      run: make test
    
  build-basic:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libpoco-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --without-ncurses --without-png --without-sdl_mixer --with-html
        make
    - name: Run CraftOSTest
      run: make test

  build-standalone:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev nodejs
    - name: Build standalone ROM
      run: |
        git clone https://github.com/MCJack123/craftos2-rom
        cd craftos2-rom
        node ../packStandaloneROM.js
        cd ..
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --with-standalone-rom=craftos2-rom/fs_standalone.cpp
        make
    - name: Run CraftOSTest
      run: make test

  build-webassembly:
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pushd ..
        git clone https://github.com/MCJack123/craftos2-rom
        git clone https://github.com/emscripten-core/emsdk
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        popd
        unzip wasm-reqs.zip
    - name: Build Lua
      run: |
        source ../emsdk/emsdk_env.sh
        git submodule update --init --recursive
        emmake make -C craftos2-lua emscripten
    - name: Build CraftOS-PC
      run: |
        source ../emsdk/emsdk_env.sh
        emconfigure ./configure --enable-wasm --with-wasm-poco=../wasm-reqs --with-wasm-openssl=../wasm-reqs --with-wasm-rom=../craftos2-rom
        emmake make
        mkdir artifact
        cp craftos.js craftos.fetch.js craftos.html.mem craftos.wasm craftos.worker.js craftos.wasm.map artifact/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CraftOS-PC-WASM
        path: artifact