name: CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      run: ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
    
  build-basic:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libpoco-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --without-ncurses --without-png --without-sdl_mixer --with-html
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      run: ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-standalone:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev nodejs
    - name: Build standalone ROM
      run: |
        git clone https://github.com/MCJack123/craftos2-rom
        cd craftos2-rom
        node ../resources/packStandaloneROM.js
        cd ..
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure --with-standalone_rom=craftos2-rom/fs_standalone.cpp
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CraftOSTest
      run: ./craftos --headless --script resources/CraftOSTest.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/CraftOSTest.log
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi

  build-cct-test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM & CC:T
      run: |
        sudo git clone https://github.com/MCJack123/craftos2-rom /usr/local/share/craftos
        git clone --branch v1.16.5-1.97.0 https://github.com/SquidDev-CC/CC-Tweaked ../CC-Tweaked
        patch -p1 -d ../CC-Tweaked < resources/CCT-Tests.patch
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-mixer-dev libhpdf-dev libpng++-dev libpoco-dev libncurses5-dev
    - name: Build Lua
      run: |
        git submodule update --init --recursive
        make -C craftos2-lua linux -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Build CraftOS-PC
      run: |
        CFLAGS=-Wall ./configure
        make -j$(grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}')
    - name: Run CC:T McFly Tests
      run: ./craftos --mount-ro test-rom=../CC-Tweaked/src/test/resources/test-rom --headless --script resources/CCT-Test-Bootstrap.lua || echo $? > ~/.retval
      continue-on-error: true
    - name: Show logs
      run: |
        cat ~/.local/share/craftos-pc/computer/0/test-log.txt
        if [ -e ~/.retval ]; then exit $(cat ~/.retval); fi
      
  build-windows:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download ROM
      run: git clone https://github.com/MCJack123/craftos2-rom "C:\Program Files\CraftOS-PC"
    - name: Install dependencies
      run: |
        curl -O https://github.com/MCJack123/PrebuiltvcpkgBinaries/archive/refs/heads/master.zip
        Expand-Archive -Force 'master.zip' '.'
        dir
        ren PrebuiltvcpkgBinaries-master vcpkg_installed
    - name: Build CraftOS-PC
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        for /f %%i in ('git rev-parse --short HEAD') do set ExternalCompilerOptions=/DCRAFTOSPC_COMMIT=\"%%i\"
        msbuild "CraftOS-PC 2.sln" /p:Configuration=ReleaseC
    - name: Run CraftOSTest
      run: |
        x64\ReleaseC\CraftOS-PC --headless --script resources\CraftOSTest.lua
        echo %ERRORLEVEL% > retval.txt
      continue-on-error: true
    - name: Show logs
      run: |
        type "%appdata\CraftOS-PC\computer\0\CraftOSTest.log"
        set /p EXITCODE=<retval.txt
        if not %EXITCODE% == 0 exit %EXITCODE%
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CraftOS-PC_${{ github.sha }}
        path: x64\ReleaseC\CraftOS-PC.exe